import SwiftUI
import AVFoundation
import Kingfisher

// MARK: - Intro Sample Screen (Sona-style layout)
struct IntroSampleScreen: View {
    let onContinue: () -> Void
    
    @State private var songs: [SunoData] = []
    @State private var selectedIndex: Int = 0
    @State private var isDownloading: Bool = false
    
    // Playback state
    @State private var player: AVPlayer? = nil
    @State private var playerObserver: Any? = nil
    @State private var isPlaying: Bool = false
    @State private var currentTime: TimeInterval = 0
    @State private var duration: TimeInterval = 0
    @State private var timeObserver: Any? = nil
    
    // Animation states
    @State private var showContent = false
    @State private var showButton = false
    
    var body: some View {
        ZStack {
            AivoSunsetBackground()
            
            VStack(spacing: 0) {
                Spacer()
                
                // Subtitle above cover
                Text("These are some songs generated by user.")
                    .font(.system(size: iPadScale(15), weight: .regular))
                    .foregroundColor(.white.opacity(0.6))
                    .multilineTextAlignment(.center)
                    .padding(.bottom, iPadScaleSmall(12))
                
                // Large selected cover with glow + play button + seekbar ring
                selectedCoverView
                
                Spacer()
                
                // Horizontal cover list
                coverListView
                    .padding(.bottom, iPadScaleSmall(20))
                
                // Title & Description
                VStack(spacing: iPadScaleSmall(12)) {
                    Text("AI POWERFUL")
                        .font(.system(size: iPadScale(32), weight: .black, design: .monospaced))
                        .foregroundColor(.white)
                        .multilineTextAlignment(.center)
                    
                    Text("Easy to create a song. No music skills needed.")
                        .font(.system(size: iPadScale(17), weight: .semibold))
                        .foregroundColor(.white.opacity(0.7))
                        .multilineTextAlignment(.center)
                        .lineLimit(2)
                        .fixedSize(horizontal: false, vertical: true)
                        .padding(.horizontal, iPadScaleSmall(32))
                }
                .fixedSize(horizontal: false, vertical: true)
                .scaleEffect(showContent ? 1.0 : 0.9)
                .opacity(showContent ? 1 : 0)
                .animation(.spring(response: 0.5, dampingFraction: 0.8).delay(0.1), value: showContent)
                .padding(.bottom, iPadScaleSmall(24))
                
                // Continue Button - matching IntroScreen
                continueButtonView
            }
            .padding(.horizontal, iPadScaleSmall(20))
        }
        .onAppear {
            loadSongs()
            showContent = true
            showButton = true
        }
        .onChange(of: songs) { newSongs in
            // Auto-select and play middle song when songs are loaded
            if !newSongs.isEmpty {
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
                    let middleIndex = min(3, newSongs.count - 1)
                    selectSong(at: middleIndex)
                }
            }
        }
        .onDisappear {
            stopPlayback()
        }
    }
    
    // MARK: - Selected Cover View
    private var selectedCoverView: some View {
        let coverSize: CGFloat = iPadScale(210)
        
        return ZStack {
            if selectedIndex < songs.count {
                let song = songs[selectedIndex]
                
                // Glow effect background
                Circle()
                    .fill(
                        RadialGradient(
                            colors: [
                                AivoTheme.Primary.orange.opacity(0.3),
                                AivoTheme.Primary.orange.opacity(0.15),
                                Color.clear
                            ],
                            center: .center,
                            startRadius: iPadScale(80),
                            endRadius: iPadScale(140)
                        )
                    )
                    .frame(width: iPadScale(280), height: iPadScale(280))
                    .blur(radius: 20)
                
                // Decorative rings
                ForEach(0..<3, id: \.self) { index in
                    Circle()
                        .stroke(
                            LinearGradient(
                                colors: [
                                    AivoTheme.Primary.orange.opacity(0.20 - Double(index) * 0.05),
                                    AivoTheme.Primary.orange.opacity(0.15 - Double(index) * 0.04)
                                ],
                                startPoint: .topLeading,
                                endPoint: .bottomTrailing
                            ),
                            lineWidth: 1.5
                        )
                        .frame(
                            width: coverSize + iPadScale(CGFloat(30 + index * 50)),
                            height: coverSize + iPadScale(CGFloat(30 + index * 50))
                        )
                        .opacity(0.45 - Double(index) * 0.15)
                }
                
                // Cover image with play button
                ZStack {
                    KFImage(URL(string: song.imageUrl))
                        .placeholder {
                            Image("cover_default_resize")
                                .resizable()
                                .aspectRatio(contentMode: .fill)
                        }
                        .resizable()
                        .aspectRatio(contentMode: .fill)
                        .frame(width: coverSize, height: coverSize)
                        .clipShape(Circle())
                        .overlay(
                            Circle()
                                .stroke(
                                    LinearGradient(
                                        colors: [AivoTheme.Primary.orange.opacity(0.2), AivoTheme.Primary.orange.opacity(0.1)],
                                        startPoint: .topLeading,
                                        endPoint: .bottomTrailing
                                    ),
                                    lineWidth: iPadScale(2)
                                )
                        )
                        .shadow(color: AivoTheme.Primary.orange.opacity(0.5), radius: 20, x: 0, y: 10)
                    
                    // Track ring (background for seekbar)
                    Circle()
                        .stroke(
                            Color.white.opacity(0.15),
                            style: StrokeStyle(lineWidth: iPadScale(6), lineCap: .round)
                        )
                        .frame(width: coverSize + iPadScale(16), height: coverSize + iPadScale(16))
                    
                    // Circular progress seekbar ring
                    Circle()
                        .trim(from: 0, to: duration > 0 ? currentTime / duration : 0)
                        .stroke(
                            AivoTheme.Primary.orange,
                            style: StrokeStyle(lineWidth: iPadScale(6), lineCap: .round)
                        )
                        .frame(width: coverSize + iPadScale(16), height: coverSize + iPadScale(16))
                        .rotationEffect(.degrees(-90))
                        .animation(.linear(duration: 0.1), value: currentTime)
                    
                    // Loading overlay
                    if isDownloading {
                        Circle()
                            .fill(Color.black.opacity(0.6))
                            .frame(width: coverSize, height: coverSize)
                        ProgressView()
                            .progressViewStyle(CircularProgressViewStyle(tint: .white))
                            .scaleEffect(DeviceScale.isIPad ? 2.0 : 1.5)
                    }
                    
                    // Play/Pause button
                    if !isDownloading {
                        Button(action: {
                            togglePlayPause()
                        }) {
                            ZStack {
                                Circle()
                                    .fill(Color.black.opacity(0.4))
                                    .frame(width: iPadScale(54), height: iPadScale(54))
                                
                                Image(systemName: isPlaying ? "pause.fill" : "play.fill")
                                    .font(.system(size: iPadScale(22)))
                                    .foregroundColor(.white)
                            }
                        }
                    }
                }
                // Tap gesture on the seekbar ring area to seek
                .gesture(
                    DragGesture(minimumDistance: 0)
                        .onEnded { value in
                            let ringSize = coverSize + iPadScale(16)
                            let center = CGPoint(x: ringSize / 2, y: ringSize / 2)
                            let location = value.location
                            // Calculate angle from top (12 o'clock position)
                            let dx = location.x - center.x
                            let dy = location.y - center.y
                            var angle = atan2(dy, dx)
                            angle += .pi / 2 // Adjust for starting at top
                            if angle < 0 { angle += 2 * .pi }
                            let progress = angle / (2 * .pi)
                            // Seek to position
                            if duration > 0 {
                                let seekTime = progress * duration
                                player?.seek(to: CMTime(seconds: seekTime, preferredTimescale: 600))
                                currentTime = seekTime
                            }
                        }
                )
                .frame(width: coverSize + iPadScale(16), height: coverSize + iPadScale(16))
                
                // Song info badge
                VStack(spacing: iPadScaleSmall(4)) {
                    HStack(spacing: iPadScaleSmall(6)) {
                        Image(systemName: "music.note")
                            .font(.system(size: iPadScale(14)))
                        Text(song.title)
                            .font(.system(size: iPadScale(15), weight: .semibold))
                            .lineLimit(1)
                    }
                    
                    Text(song.modelName.isEmpty ? "AIVO" : song.modelName)
                        .font(.system(size: iPadScale(13)))
                        .foregroundColor(.white.opacity(0.7))
                        .lineLimit(1)
                }
                .foregroundColor(.white)
                .padding(.horizontal, iPadScaleSmall(16))
                .padding(.vertical, iPadScaleSmall(10))
                .background(Color.white.opacity(0.1))
                .cornerRadius(iPadScale(20))
                .offset(y: coverSize / 2 + iPadScale(35))
            }
        }
        .frame(height: iPadScale(340))
        .padding(.bottom, iPadScale(20))
    }
    
    // MARK: - Cover List View
    private var coverListView: some View {
        ScrollViewReader { proxy in
            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: iPadScaleSmall(12)) {
                    ForEach(Array(songs.enumerated()), id: \.element.id) { index, song in
                        coverItem(song: song, index: index)
                            .id(index)
                    }
                }
                .padding(.horizontal, max(iPadScale(20), (UIScreen.main.bounds.width - iPadScale(100)) / 2))
            }
            .frame(height: iPadScale(130))
            .onChange(of: selectedIndex) { newIndex in
                withAnimation(.spring(response: 0.3, dampingFraction: 0.8)) {
                    proxy.scrollTo(newIndex, anchor: .center)
                }
            }
        }
    }
    
    private func coverItem(song: SunoData, index: Int) -> some View {
        let itemSize: CGFloat = selectedIndex == index ? iPadScale(85) : iPadScale(70)
        
        return Button(action: {
            selectSong(at: index)
        }) {
            KFImage(URL(string: song.imageUrl))
                .placeholder {
                    Image("cover_default_resize")
                        .resizable()
                        .aspectRatio(contentMode: .fill)
                }
                .resizable()
                .aspectRatio(contentMode: .fill)
                .frame(width: itemSize, height: itemSize)
                .clipShape(Circle())
                .overlay(
                    Circle()
                        .stroke(
                            selectedIndex == index ?
                            LinearGradient(
                                colors: [AivoTheme.Primary.orange, AivoTheme.Primary.orange.opacity(0.5)],
                                startPoint: .topLeading,
                                endPoint: .bottomTrailing
                            ) :
                            LinearGradient(
                                colors: [Color.clear],
                                startPoint: .topLeading,
                                endPoint: .bottomTrailing
                            ),
                            lineWidth: selectedIndex == index ? iPadScale(3) : 0
                        )
                )
                .scaleEffect(selectedIndex == index ? 1.0 : 0.9)
                .opacity(selectedIndex == index ? 1.0 : 0.6)
                .shadow(
                    color: selectedIndex == index ? AivoTheme.Primary.orange.opacity(0.5) : Color.clear,
                    radius: 10,
                    x: 0,
                    y: 5
                )
                .animation(.spring(response: 0.3, dampingFraction: 0.7), value: selectedIndex)
                .padding(.vertical, iPadScaleSmall(15))
        }
    }
    
    // MARK: - Continue Button (matching IntroScreen continueButton exactly)
    private var continueButtonView: some View {
        Button(action: {
            stopPlayback()
            onContinue()
        }) {
            HStack {
                Text("Continue")
                    .font(.system(size: iPadScale(17), weight: .semibold))
                
                Image(systemName: "arrow.right")
                    .font(.system(size: iPadScale(17)))
            }
            .foregroundColor(.black)
            .frame(maxWidth: .infinity)
            .frame(height: iPadScale(50))
            .background(AivoTheme.Primary.orange)
            .cornerRadius(iPadScale(12))
            .shadow(color: AivoTheme.Shadow.orange, radius: 10, x: 0, y: 0)
        }
        .padding(.bottom, iPadScaleSmall(30))
        .opacity(showButton ? 1 : 0)
        .offset(y: showButton ? 0 : 40)
        .animation(.easeOut(duration: 0.9).delay(1.0), value: showButton)
    }
    
    // MARK: - Data Loading
    private func loadSongs() {
        // Get 7 random songs from BEST_AIVO_SONGS
        let bestSongs = RemoteConfigManager.shared.bestAivoSongsList
        if bestSongs.count >= 7 {
            songs = Array(bestSongs.shuffled().prefix(7))
        } else {
            songs = bestSongs.shuffled()
        }
    }
    
    // MARK: - Actions
    private func selectSong(at index: Int) {
        guard index < songs.count else { return }
        
        withAnimation {
            selectedIndex = index
        }
        
        let song = songs[index]
        playSong(song)
    }
    
    private func togglePlayPause() {
        if isPlaying {
            player?.pause()
            isPlaying = false
        } else {
            player?.play()
            isPlaying = true
        }
    }
    
    private func playSong(_ song: SunoData) {
        // Stop current
        stopPlayback()
        
        isDownloading = true
        
        guard let audioUrl = URL(string: song.audioUrl) else {
            isDownloading = false
            return
        }
        
        let playerItem = AVPlayerItem(url: audioUrl)
        player = AVPlayer(playerItem: playerItem)
        
        // Observe when ready to play
        playerObserver = playerItem.observe(\.status, options: [.new]) { item, _ in
            DispatchQueue.main.async {
                switch item.status {
                case .readyToPlay:
                    self.isDownloading = false
                    self.isPlaying = true
                    self.player?.play()
                    
                    // Get duration
                    Task {
                        do {
                            let dur = try await item.asset.load(.duration)
                            await MainActor.run {
                                if dur.seconds.isFinite {
                                    self.duration = dur.seconds
                                }
                            }
                        } catch {
                            Logger.e("❌ [IntroSampleScreen] Duration load error: \(error)")
                        }
                    }
                case .failed:
                    Logger.e("❌ [IntroSampleScreen] Failed to load: \(item.error?.localizedDescription ?? "Unknown")")
                    self.isDownloading = false
                default:
                    break
                }
            }
        }
        
        // Time observer
        let interval = CMTime(seconds: 0.1, preferredTimescale: 600)
        timeObserver = player?.addPeriodicTimeObserver(forInterval: interval, queue: .main) { time in
            self.currentTime = time.seconds
        }
        
        // Observe playback end
        NotificationCenter.default.addObserver(
            forName: .AVPlayerItemDidPlayToEndTime,
            object: playerItem,
            queue: .main
        ) { _ in
            // Auto-play next
            if self.selectedIndex < self.songs.count - 1 {
                self.selectSong(at: self.selectedIndex + 1)
            } else {
                self.isPlaying = false
            }
        }
    }
    
    private func stopPlayback() {
        if let obs = timeObserver {
            player?.removeTimeObserver(obs)
            timeObserver = nil
        }
        player?.pause()
        player = nil
        if let observer = playerObserver as? NSKeyValueObservation {
            observer.invalidate()
        }
        playerObserver = nil
        isPlaying = false
        isDownloading = false
        currentTime = 0
        duration = 0
        NotificationCenter.default.removeObserver(self, name: .AVPlayerItemDidPlayToEndTime, object: nil)
    }
}

// MARK: - Preview
struct IntroSampleScreen_Previews: PreviewProvider {
    static var previews: some View {
        IntroSampleScreen {
            print("Continue tapped")
        }
    }
}
